name: Recipe Website CI/CD # Nama workflow Anda

on:
  push:
    branches: [ "main" ] # Trigger saat ada push ke branch main
  pull_request:
    branches: [ "main" ] # Trigger saat ada Pull Request ke branch main

permissions:
  contents: read # Memberikan izin baca untuk konten repositori

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} # Variabel environment dari secrets
  SERVICE_NAME: recipe-website
  REGION: asia-southeast1

jobs:
  test: # Nama job untuk pengujian
    runs-on: ubuntu-latest # Runner yang digunakan

    services: # Konfigurasi service container untuk MySQL
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: recipedb_test
          MYSQL_USER: recipeadmin
          MYSQL_PASSWORD: kod12345
        ports:
          - 3306:3306 # Port mapping: host:container
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 # Health check untuk MySQL

    steps:
    - uses: actions/checkout@v4 # Menggunakan actions/checkout versi 4 yang lebih baru

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }} # Menggunakan direktori cache composer
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }} # Key cache yang lebih robust
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Set up PHP # Mengatur PHP sesuai kebutuhan proyek Anda
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, gd, pdo_mysql
        coverage: xdebug # Untuk code coverage dengan PHPUnit
        tools: composer:v2

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress

    - name: Wait for MySQL to be ready # <--- INI INDENTASI YANG BENAR
      run: |
        echo "Waiting for MySQL to be fully ready..."
        for i in $(seq 1 60); do # Coba hingga 60 kali (total 60 detik)
          if mysqladmin ping -h mysql --silent; then
            echo "MySQL is ready!"
            break
          fi
          echo "Still waiting for MySQL... ($i/60)"
          sleep 1
        done
        mysqladmin ping -h mysql || { echo "MySQL did not become ready in time!"; exit 1; }
      env:
        MYSQL_PWD: rootpassword

    - name: Create test database and import schema
      run: |
        # Gunakan 'mysql' sebagai host untuk konsistensi
        mysql -h mysql -u root -prootpassword recipedb_test < recipedb.sql
      # Hapus baris 'env: MYSQL_READY_DELAY: 10' karena tidak digunakan
      # env:
      #   MYSQL_READY_DELAY: 10

    - name: Run PHPUnit tests
      run: |
        ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

    - name: PHP Syntax Check
      run: find . -type f -name "*.php" -exec php -l {} \;

    - name: PHP Code Sniffer
      run: |
        ./vendor/bin/phpcs --standard=PSR12 --extensions=php .

    - name: PHP Mess Detector
      run: |
        ./vendor/bin/phpmd . text cleancode,codesize,controversial,design,naming,unusedcode